### ISSUE TITLE
Include a link to PoBBuddy

### ISSUE THREAD

**Issue by Biggoron144** [aggixx/PoBPreviewBot#8]
https://poe.technology/poebuddy/ is a website that provides an interactive snapshot of the Path of Building build. It'd be great if your bot would also link the PoEBuddy version of the build so people can check things without loading up the program!

**Comment by aggixx** [comment]
Added in c77ffe2343680d05cd1d96cd2b9ab40912fd363f. Thanks for the suggestion.
